# Generated by Django 2.0.3 on 2018-06-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180622_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='meals', to='orders.Toppings'),
        ),
    ]
